ALTER TABLE public."Product" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."BrandPrefix" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ProductIdentifier" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."InventorySnapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SyncRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."SyncRunItem" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ActivityLog" ENABLE ROW LEVEL SECURITY;
